name: test

on:
  push:
  pull_request:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  LOG_LEVEL: debug

jobs:
  preset:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        file:
          - default
          - renovate-config
          - merge-queue
    env:
      RENOVATE_CONFIG_FILE: ${{ matrix.file }}.json

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: testing ${{ matrix.file }}
        run: npx -p renovate renovate-config-validator
